### ISSUE TITLE
Please make a new branch for laravel 5 :)

### ISSUE THREAD

**Issue by jonathan-bird** [infi-nl/laravel-feature-toggle#1]

**Comment by edeckers** [comment]
We're not actively maintaining this project. I will happily test and accept pull-requests though!

**Comment by edeckers** [comment]
I created separate branches for Laravel 4.x and Laravel 5.x and modified the latter to work under L5/Homestead. Before I can build a release I will have to wait for @JoshuaEstes  to accept PR JoshuaEstes/FeatureToggle#9 though, because without it my code breaks.

Also I am planning on moving the Laravel 5.x branch to master as soon as possible.

**Comment by JoshuaEstes** [comment]
I wondered who has been using the hell out of this =) I have been working on and thinking about doing a new major version release. I'd be happy to get anyone's input on goods and bads of the library.

**Comment by edeckers** [comment]
There are separate Laravel 4.0 and 5.0 branches now, and master is updated to Laravel 5.0

**Comment by jonathan-bird** [comment]
We are about to use this heavily :100: :+1:
